controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    imu_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

imu_broadcaster:
  ros__parameters:
    sensor_name: "imu_sensor"
    frame_id: imu_link
