image_width: 640
image_height: 480
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [503.44365,   0.     , 318.62296,
           0.     , 506.93496, 250.87916,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.127547, -0.220683, 0.004405, 0.002068, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [510.97653,   0.     , 319.34766,   0.     ,
           0.     , 515.49915, 252.02707,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
