controller_manager:
  ros__parameters:
    update_rate: 30  # Hz

    diff_controller:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_controller:
  ros__parameters:
    publish_rate: 50.0
    left_wheel_names: ['front_left_wheel_joint']
    right_wheel_names: ['front_right_wheel_joint']
    wheels_per_side: 1
    wheel_separation: 0.3
    wheel_radius: 0.05
    odom_frame_id: odom
    base_frame_id: base_link
    enable_odom_tf: true
    use_stamped_vel: false


# joint_state_broadcaster:
#   ros__parameters: